apiVersion: v1
kind: Pod
metadata:
  name: init-demo2
  labels:
    name: init-demo2
spec:
  containers:
  - name: nginx
    image: nginx
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 82
