apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx #de service tro toi deployment qua ten nay
  name: nginx-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx  # cai nay phai giong nhau
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - image: nginx
          name: nginx
          ports:
            - containerPort: 80
